services:
#    eher_quero_ser_voluntario_domain.example:
#        class: Eher\QueroSerVoluntario\Bundle\DomainBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    mail_manager:
        class: Eher\QueroSerVoluntario\Bundle\DomainBundle\Mail\MailManager
        arguments: [@mailer]
