tools:
    php_cpd: true
    php_cs_fixer: true
    php_loc: true
    php_mess_detector: true
    php_analyzer:
        filter:
            excluded_paths: ["*/Tests/*","*/spec/*","*/app/*","*/web/*"]
    sensiolabs_security_checker: true