code:
    build: .
    links:
        - db

php:
    build: docker/php-fpm
    volumes_from:
        - code
    links:
        - db

nginx:
    build: docker/nginx
    volumes_from:
        - code
    links:
        - php
    ports:
        - 81:80
    environment:
        - VIRTUAL_HOST=*.queroservoluntario.com,queroservoluntario.com

db:
    image: mysql:5.7
    environment:
        - MYSQL_ROOT_PASSWORD
    ports:
        - 3306:3306

loadbalancer:
    image: jwilder/nginx-proxy
    volumes:
        - /var/run/docker.sock:/tmp/docker.sock
    links:
        - nginx
    ports:
        - 80:80
