code:
    build: .
    environment:
        - SYMFONY__CONTACT__EMAIL
        - SYMFONY__FRAMEWORK__LOCALE
        - SYMFONY__FRAMEWORK__SECRET
        - SYMFONY__MAILGUN__DOMAIN
        - SYMFONY__MAILGUN__KEY
    volumes_from:
        - data
data:
    build: docker/php-fpm
    command: 'true'
    volumes:
        - /var/www/symfony/database
        - /var/www/symfony/vendor
nginx:
    build: docker/nginx
    environment:
        - 'VIRTUAL_HOST=*.queroservoluntario.com,queroservoluntario.com'
    expose:
        - '443'
    links:
        - php
    ports:
        - '80'
    volumes_from:
        - code
php:
    build: docker/php-fpm
    environment:
        - SYMFONY__CONTACT__EMAIL
        - SYMFONY__FRAMEWORK__LOCALE
        - SYMFONY__FRAMEWORK__SECRET
        - SYMFONY__MAILGUN__DOMAIN
        - SYMFONY__MAILGUN__KEY
    volumes_from:
        - code
