code:
    build: .

php:
    build: docker/php-fpm
    mem_limit: 128m
    volumes_from:
        - code

nginxdebug:
    build: docker/nginx-debug
    mem_limit: 16m
    volumes_from:
        - code
    links:
        - php
    environment:
        - VIRTUAL_HOST=dev.queroservoluntario.com

nginx:
    build: docker/nginx
    mem_limit: 16m
    volumes_from:
        - code
    links:
        - php
    environment:
        - VIRTUAL_HOST=*.queroservoluntario.com,queroservoluntario.com
