code:
    build: .
    environment:
        - SYMFONY__CONTACT__EMAIL=tequeremosvoluntario@gmail.com
        - SYMFONY__FRAMEWORK__LOCALE=pt_BR
        - SYMFONY__FRAMEWORK__SECRET=random-secret-key
        - SYMFONY__MAILGUN__DOMAIN=queroservoluntario.com
        - SYMFONY__MAILGUN__KEY=8hdR+Y3bMkrW2m9Wp7PMflw25FRml16/Ja87bq0SAnk=
    volumes_from:
        - data
data:
    build: docker/php-fpm
    command: 'true'
    volumes:
        - /var/www/symfony/database
        - /var/www/symfony/vendor
nginx:
    build: docker/nginx
    environment:
        - 'VIRTUAL_HOST=*.queroservoluntario.com,queroservoluntario.com'
    expose:
        - '443'
    links:
        - php
    ports:
        - '80'
    volumes_from:
        - code
php:
    build: docker/php-fpm
    environment:
        - SYMFONY__CONTACT__EMAIL=tequeremosvoluntario@gmail.com
        - SYMFONY__FRAMEWORK__LOCALE=pt_BR
        - SYMFONY__FRAMEWORK__SECRET=random-secret-key
        - SYMFONY__MAILGUN__DOMAIN=queroservoluntario.com
        - SYMFONY__MAILGUN__KEY=8hdR+Y3bMkrW2m9Wp7PMflw25FRml16/Ja87bq0SAnk=
    volumes_from:
        - code
