app:
    resource: "@EherQueroSerVoluntarioFrontendBundle/Controller/"
    type: annotation

homepage:
    path:  /
    defaults:
        _controller: "FrameworkBundle:Template:template"
        template: "EherQueroSerVoluntarioFrontendBundle:Default:home.html.twig"

sobre:
    path:  /sobre
    defaults:
        _controller: "FrameworkBundle:Template:template"
        template: "EherQueroSerVoluntarioFrontendBundle:Default:sobre.html.twig"

contato:
    path:  /contato
    defaults:
        _controller: "FrameworkBundle:Template:template"
        template: "EherQueroSerVoluntarioFrontendBundle:Default:contato.html.twig"

voluntario_cadastrar:
    path:  /voluntarios/cadastrar
    defaults: { _controller: "EherQueroSerVoluntarioFrontendBundle:Default:newVoluntarioForm" }

voluntario_criar:
    path:  /voluntarios
    defaults: { _controller: "EherQueroSerVoluntarioFrontendBundle:Default:createVoluntario" }
    requirements: { _method: post }

voluntario_parabens:
    path:  /voluntarios/parabens
    defaults:
        _controller: "FrameworkBundle:Template:template"
        template: "EherQueroSerVoluntarioFrontendBundle:Default:voluntarioParabens.html.twig"

brasil:
    path:  /brasil
    defaults: { _controller: "EherQueroSerVoluntarioFrontendBundle:Estado:index" }

cidade_em_estado:
    path:  /cidades/em/{estado}
    defaults: { _controller: "EherQueroSerVoluntarioFrontendBundle:Cidade:emEstado" }
