admin:
    pattern:  /admin
    defaults:
        _controller: "FrameworkBundle:Template:template"
        template: "EherQueroSerVoluntarioBundle:Admin:home.html.twig"

homepage:
    pattern:  /
    defaults:
        _controller: "FrameworkBundle:Template:template"
        template: "EherQueroSerVoluntarioBundle:Default:home.html.twig"

sobre:
    pattern:  /sobre
    defaults:
        _controller: "FrameworkBundle:Template:template"
        template: "EherQueroSerVoluntarioBundle:Default:sobre.html.twig"

buscar:
    pattern:  /entidades
    defaults: { _controller: "EherQueroSerVoluntarioBundle:Default:buscarEntidade" }

entidades:
    pattern:  /{stateName}/{cityName}
    defaults: { _controller: "EherQueroSerVoluntarioBundle:Default:entidadesByCityAndState" }
    requirements:
            stateName: \w\w

contato:
    pattern:  /contato
    defaults:
        _controller: "FrameworkBundle:Template:template"
        template: "EherQueroSerVoluntarioBundle:Default:contato.html.twig"

voluntario_cadastrar:
    pattern:  /voluntarios/cadastrar
    defaults: { _controller: "EherQueroSerVoluntarioBundle:Default:newVoluntarioForm" }
    requirements: { _method: get }

voluntario_criar:
    pattern:  /voluntarios/cadastrar
    defaults: { _controller: "EherQueroSerVoluntarioBundle:Default:createVoluntario" }
    requirements: { _method: post }

voluntario_parabens:
    pattern:  /voluntarios/parabens
    defaults:
        _controller: "FrameworkBundle:Template:template"
        template: "EherQueroSerVoluntarioBundle:Default:voluntarioParabens.html.twig"

entidade_cadastrar:
    pattern:  /entidades/cadastrar
    defaults: { _controller: "EherQueroSerVoluntarioBundle:Default:newEntidadeForm" }
    requirements: { _method: get }

entidade_criar:
    pattern:  /entidades/cadastrar
    defaults: { _controller: "EherQueroSerVoluntarioBundle:Default:createEntidade" }
    requirements: { _method: post }

entidade_parabens:
    pattern:  /entidades/parabens
    defaults:
        _controller: "FrameworkBundle:Template:template"
        template: "EherQueroSerVoluntarioBundle:Default:entidadeParabens.html.twig"

brasil:
    pattern:  /brasil
    defaults: { _controller: "EherQueroSerVoluntarioBundle:Estado:index" }

cidade_em_estado:
    pattern:  /cidades/em/{estado}
    defaults: { _controller: "EherQueroSerVoluntarioBundle:Cidade:emEstado" }

login:
    pattern: /login
    defaults: { _controller: EherQueroSerVoluntarioBundle:Security:login }

login_check:
    pattern: /login_check

logout:
    pattern:   /logout
