homepage:
    pattern:  /
    defaults: { _controller: "EherQueroSerVoluntarioBundle:Default:index" }

sobre:
    pattern:  /sobre
    defaults: { _controller: "EherQueroSerVoluntarioBundle:Default:sobre" }

buscar:
    pattern:  /entidade/buscar
    defaults: { _controller: "EherQueroSerVoluntarioBundle:Default:buscar" }

brasil:
    pattern:  /brasil
    defaults: { _controller: "EherQueroSerVoluntarioBundle:Default:brasil" }

contato:
    pattern:  /contato
    defaults: { _controller: "EherQueroSerVoluntarioBundle:Default:contato" }

voluntario_parabens:
    pattern:  /voluntario/parabens
    defaults: { _controller: "EherQueroSerVoluntarioBundle:Default:voluntarioParabens" }

entidade_parabens:
    pattern:  /entidade/parabens
    defaults: { _controller: "EherQueroSerVoluntarioBundle:Default:entidadeParabens" }
