services:
    rest_client:
        class: chegamos\rest\client\Guzzle

    apontador_api_basic_auth:
        class: chegamos\rest\auth\BasicAuth
        arguments: 
            - %apontador_api_consumer_key%
            - %apontador_api_consumer_secret%

    chegamos_config:
        class: chegamos\entity\Config
        calls:
            - [setBasicAuth, [@apontador_api_basic_auth]]
            - [setRestClient, [@rest_client]]
            - [setBaseUrl, [%apontador_api_base_url%]]

    place_repository:
        class: chegamos\entity\repository\PlaceRepository
        arguments: [@chegamos_config]

    mail_manager:
        class: Eher\QueroSerVoluntario\Bundle\Model\MailManager
        arguments: [@mailer]
