Eher\QueroSerVoluntario\Bundle\Entity\Voluntario:
    properties:
        nome:
            - NotBlank:
                message: "O campo Nome é obrigatório"
        email:
            - NotBlank:
                message: "O campo Email é obrigatório"
            - Email:
                message: "O email digitado não é válido"
                checkMX: true

Eher\QueroSerVoluntario\Bundle\Entity\Entidade:
    properties:
        nome:
            - NotBlank:
                message: "O campo Nome é obrigatório"
        endereco:
            - NotBlank:
                message: "O campo Endereço é obrigatório"
        bairro:
            - NotBlank:
                message: "O campo Bairro é obrigatório"

Eher\QueroSerVoluntario\Bundle\Entity\Vaga:
    properties:
        nome:
            - NotBlank:
                message: "O campo Nome é obrigatório"
