Eher\QueroSerVoluntario\Bundle\Entity\Voluntario:
    properties:
        nome:
            - NotBlank:
                message: "Nome é obrigatório"
        email:
            - NotBlank:
                message: "Email é obrigatório"
            - Email:
                message: "O email \"{{ value }}\" é inválido."
                checkMX: true

Eher\QueroSerVoluntario\Bundle\Entity\Entidade:
    properties:
        nome:
            - NotBlank:
                message: "Nome é obrigatório"
        endereco:
            - NotBlank:
                message: "Endereço é obrigatório"
        bairro:
            - NotBlank:
                message: "Bairro é obrigatório"

Eher\QueroSerVoluntario\Bundle\Entity\Vaga:
    properties:
        nome:
            - NotBlank:
                message: "Nome é obrigatório"
