Eher\QueroSerVoluntario\Bundle\Entity\Voluntario:
    properties:
        nome:
            - NotBlank:
                message: "O campo Nome é obrigatório"
        email:
            - NotBlank:
                message: "O campo Email é obrigatório"
            - Email:
                message: "O email digitado não é válido"
                checkMX: true
        telefone:
            - NotBlank:
                message: "O campo Telefone é obrigatório"
            - Regex:
                pattern: "/\(\d{2}\)\ \d{4,5}-\d{4}/"
                message: "O Telefone digitado não é válido - Tente digitar no formato (00) 0000-0000"
        cidade:
            - NotBlank:
                message: "O campo Cidade é obrigatório"

Eher\QueroSerVoluntario\Bundle\Entity\Entidade:
    properties:
        nome:
            - NotBlank:
                message: "O campo Nome é obrigatório"
        endereco:
            - NotBlank:
                message: "O campo Endereço é obrigatório"
        bairro:
            - NotBlank:
                message: "O campo Bairro é obrigatório"
        cidade:
            - NotBlank:
                message: "O campo Cidade é obrigatório"
        cep:
            - NotBlank:
                message: "O campo CEP é obrigatório"
            - Regex:
                pattern: "/\d{5}-\d{3}/"
                message: "O CEP digitado não é válido - Tente digitar no formato 00000-000"
        email:
            - NotBlank:
                message: "O campo Email é obrigatório"
            - Email:
                message: "O email digitado não é válido"
                checkMX: true

Eher\QueroSerVoluntario\Bundle\Entity\Vaga:
    properties:
        nome:
            - NotBlank:
                message: "O campo Nome é obrigatório"
