Eher\QueroSerVoluntario\Bundle\Entity\Voluntario:
    properties:
        nome:
            - NotBlank:
                message: "Nome é obrigatório"
        email:
            - NotBlank:
                message: "Email é obrigatório"
            - Email:
                message: "O email \"{{ value }}\" é inválido."
                checkMX: true
        cidade:
            - NotBlank:
                message: "Cidade é obrigatório"
        estado:
            - NotBlank:
                message: "Estado é obrigatório"

Eher\QueroSerVoluntario\Bundle\Entity\Entidade:
    properties:
        nome:
            - NotBlank:
                message: "Nome é obrigatório"
        endereco:
            - NotBlank:
                message: "Endereço é obrigatório"
        numero:
            - NotBlank:
                message: "Número é obrigatório"
        complemento:
            - NotBlank:
                message: "Complemento é obrigatório"
        cep:
            - NotBlank:
                message: "CEP é obrigatório"
        bairro:
            - NotBlank:
                message: "Bairro é obrigatório"
        cidade:
            - NotBlank:
                message: "Cidade é obrigatório"
        estado:
            - NotBlank:
                message: "Estado é obrigatório"
        telefone:
            - NotBlank:
                message: "Telefone é obrigatório"
