EherQueroSerVoluntarioBundle:
    resource: "@EherQueroSerVoluntarioBundle/Resources/config/routing.yml"
    prefix:   /

EherQueroSerVoluntarioBundle_voluntario:
    resource: "@EherQueroSerVoluntarioBundle/Resources/config/routing/voluntario.yml"
    prefix:   /admin/voluntarios

EherQueroSerVoluntarioBundle_entidade:
    resource: "@EherQueroSerVoluntarioBundle/Resources/config/routing/entidade.yml"
    prefix:   /admin/entidades

EherQueroSerVoluntarioBundle_vaga:
    resource: "@EherQueroSerVoluntarioBundle/Resources/config/routing/vaga.yml"
    prefix:   /admin/vagas

EherQueroSerVoluntarioBundle_mensagem:
    resource: "@EherQueroSerVoluntarioBundle/Resources/config/routing/mensagem.yml"
    prefix:   /admin/mensagens

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
