eher_quero_ser_voluntario_admin:
    resource: "@EherQueroSerVoluntarioAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

eher_quero_ser_voluntario_api:
    resource: "@EherQueroSerVoluntarioApiBundle/Resources/config/routing.yml"
    prefix:   /api

eher_quero_ser_voluntario_auth:
    resource: "@EherQueroSerVoluntarioSecurityBundle/Resources/config/routing.yml"
    prefix:   /

eher_quero_ser_voluntario_frontend:
    resource: "@EherQueroSerVoluntarioFrontendBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
