EherQueroSerVoluntarioBundle:
    resource: "@EherQueroSerVoluntarioBundle/Resources/config/routing.yml"
    prefix:   /


EherQueroSerVoluntarioBundle_voluntario:
    resource: "@EherQueroSerVoluntarioBundle/Resources/config/routing/voluntario.yml"
    prefix:   /voluntario

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
