EherQueroSerVoluntarioBundle:
    resource: "@EherQueroSerVoluntarioBundle/Resources/config/routing.yml"
    prefix:   /

EherQueroSerVoluntarioBundle_voluntario:
    resource: "@EherQueroSerVoluntarioBundle/Resources/config/routing/voluntario.yml"
    prefix:   /voluntario

EherQueroSerVoluntarioBundle_entidade:
    resource: "@EherQueroSerVoluntarioBundle/Resources/config/routing/entidade.yml"
    prefix:   /entidade

EherQueroSerVoluntarioBundle_estado:
    resource: "@EherQueroSerVoluntarioBundle/Resources/config/routing/estado.yml"
    prefix:   /estado

EherQueroSerVoluntarioBundle_cidade:
    resource: "@EherQueroSerVoluntarioBundle/Resources/config/routing/cidade.yml"
    prefix:   /cidade

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
