jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm:   sha1
            iterations: 1
            encode_as_base64: false

    providers:
        in_memory:
            memory:
                users:
                    %admin_web_username%: { password: %admin_web_password%, roles: 'ROLE_ADMIN' }

    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login: ~
            logout: ~

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/voluntarios/cadastrar, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/voluntarios/parabens, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/voluntarios, roles: ROLE_ADMIN }
        - { path: ^/vagas, roles: ROLE_ADMIN }

