jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        in_memory:
            memory:
                users:
                    admin: { password: 123, roles: 'ROLE_ADMIN' }

    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login: ~
            logout: ~

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }

