security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        in_memory:
            memory:
                users:
                    %admin_web_username%: { password: %admin_web_password%, roles: 'ROLE_ADMIN' }

    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login: ~
            logout: ~

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }

