fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

eher_quero_ser_voluntario_auth_login:
    path:  /oauth/v2/auth_login
    defaults: { _controller: EherQueroSerVoluntarioSecurityBundle:Security:login }

eher_quero_ser_voluntario_auth_check:
    path:  /oauth/v2/auth_login_check
    defaults: { _controller: EherQueroSerVoluntarioSecurityBundle:Security:loginCheck }

login:
    path: /login
    defaults: { _controller: EherQueroSerVoluntarioSecurityBundle:Security:login }

login_check:
    path: /login_check

logout:
    path:   /logout
