homepage:
    pattern:  /
    defaults: { _controller: EherVoluntariosBundle:Voluntarios:welcome }

Voluntarios:
    pattern:  /Voluntarios
    defaults: { _controller: EherVoluntariosBundle:Voluntarios:index }
