cidade:
    pattern:  /
    defaults: { _controller: "EherQueroSerVoluntarioBundle:Cidade:index" }

cidade_show:
    pattern:  /{id}
    defaults: { _controller: "EherQueroSerVoluntarioBundle:Cidade:show" }

cidade_em_estado:
    pattern:  /em/{estado}
    defaults: { _controller: "EherQueroSerVoluntarioBundle:Cidade:emEstado" }
