cidade:
    pattern:  /
    defaults: { _controller: "EherQueroSerVoluntarioBundle:Cidade:index" }

cidade_show:
    pattern:  /{id}
    defaults: { _controller: "EherQueroSerVoluntarioBundle:Cidade:show" }
