mensagem:
    pattern: /
    defaults:
        _controller: "FrameworkBundle:Template:template"
        template: "EherQueroSerVoluntarioBundle:Mensagem:index.html.twig"

mensagem_welcome:
    pattern: /bem-vindo
    defaults: { _controller: "EherQueroSerVoluntarioBundle:Mensagem:welcome" }

mensagem_recomendation:
    pattern: /recomendacao
    defaults: { _controller: "EherQueroSerVoluntarioBundle:Mensagem:recomendation" }

mensagem_news:
    pattern: /novidades
    defaults: { _controller: "EherQueroSerVoluntarioBundle:Mensagem:news" }
