vaga_new:
    pattern:  /cadastrar
    defaults: { _controller: "EherQueroSerVoluntarioBundle:Vaga:new" }
    requirements: { _method: get }

vaga_create:
    pattern:  /
    defaults: { _controller: "EherQueroSerVoluntarioBundle:Vaga:create" }
    requirements: { _method: post }

vaga:
    pattern:  /
    defaults: { _controller: "EherQueroSerVoluntarioBundle:Vaga:index" }

vaga_show:
    pattern:  /{id}
    defaults: { _controller: "EherQueroSerVoluntarioBundle:Vaga:show" }
    requirements: { _method: get }

vaga_edit:
    pattern:  /{id}/editar
    defaults: { _controller: "EherQueroSerVoluntarioBundle:Vaga:edit" }
    requirements: { _method: get }

vaga_update:
    pattern:  /{id}
    defaults: { _controller: "EherQueroSerVoluntarioBundle:Vaga:update" }
    requirements: { _method: post|put }

vaga_delete:
    pattern:  /{id}
    defaults: { _controller: "EherQueroSerVoluntarioBundle:Vaga:delete" }
    requirements: { _method: delete }
