voluntario_new:
    pattern:  /cadastrar
    defaults: { _controller: "EherQueroSerVoluntarioBundle:Voluntario:new" }
    requirements: { _method: get }

voluntario_create:
    pattern:  /
    defaults: { _controller: "EherQueroSerVoluntarioBundle:Voluntario:create" }
    requirements: { _method: post }

voluntario:
    pattern:  /
    defaults: { _controller: "EherQueroSerVoluntarioBundle:Voluntario:index" }
    requirements: { _method: get }

voluntario_show:
    pattern:  /{id}
    defaults: { _controller: "EherQueroSerVoluntarioBundle:Voluntario:show" }
    requirements: { _method: get }

voluntario_edit:
    pattern:  /{id}/editar
    defaults: { _controller: "EherQueroSerVoluntarioBundle:Voluntario:edit" }
    requirements: { _method: get }

voluntario_update:
    pattern:  /{id}
    defaults: { _controller: "EherQueroSerVoluntarioBundle:Voluntario:update" }
    requirements: { _method: post|put }

voluntario_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "EherQueroSerVoluntarioBundle:Voluntario:delete" }
    requirements: { _method: delete }

voluntario_mail:
    pattern:  /{id}/mail
    defaults: { _controller: "EherQueroSerVoluntarioBundle:Voluntario:mail" }
    requirements: { _method: post }

