Eher\QueroSerVoluntario\Bundle\Entity\Voluntario:
  type: entity
  table: null
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    nome:
      type: string
      length: '50'
    email:
      type: string
      length: '100'
    uf:
      type: string
      length: '2'
    cidade:
      type: string
      length: '50'
  lifecycleCallbacks: {  }
