admin:
    path:  /
    defaults:
        _controller: "FrameworkBundle:Template:template"
        template: "EherQueroSerVoluntarioAdminBundle:Admin:home.html.twig"

EherQueroSerVoluntarioBundle_voluntario:
    resource: "@EherQueroSerVoluntarioAdminBundle/Resources/config/routing/voluntario.yml"
    prefix:   /voluntarios

EherQueroSerVoluntarioBundle_entidade:
    resource: "@EherQueroSerVoluntarioAdminBundle/Resources/config/routing/entidade.yml"
    prefix:   /entidades

EherQueroSerVoluntarioBundle_vaga:
    resource: "@EherQueroSerVoluntarioAdminBundle/Resources/config/routing/vaga.yml"
    prefix:   /vagas

EherQueroSerVoluntarioBundle_mensagem:
    resource: "@EherQueroSerVoluntarioAdminBundle/Resources/config/routing/mensagem.yml"
    prefix:   /mensagens

