---
- hosts: all
  sudo: true
  vars:
    web_server: nginxphp
    servername: queroservoluntario.com www.queroservoluntario.com dev.queroservoluntario.com 192.168.33.99
    timezone: Europe/Amsterdam
  vars_files:
    - vars/mysql.yml
    - vars/common.yml
    - [ "vars/nginxphp.yml", "vars/ws_defaults.yml" ]
  roles:
    - init
    - php5-cli
    - nginx
    - php5-fpm
    - mysql
    - composer
    - phpcommon
    - php-pecl
    - app
