ALTER TABLE Vaga ADD online TINYINT(1) NOT NULL;
ALTER TABLE Vaga CHANGE email_template como_aplicar LONGTEXT NOT NULL;
ALTER TABLE Entidade ADD site VARCHAR(50) NOT NULL, ADD email VARCHAR(50) NOT NULL, CHANGE cep cep VARCHAR(9) NOT NULL;
ALTER TABLE Voluntario ADD telefone VARCHAR(50) NOT NULL;
