ALTER TABLE Entidade ADD cidade_id INT DEFAULT NULL, ADD created_at DATETIME NOT NULL, DROP numero, DROP complemento, DROP cidade, DROP estado;
ALTER TABLE Entidade ADD CONSTRAINT FK_1A5F84849586CC8 FOREIGN KEY (cidade_id) REFERENCES Cidade (id);
CREATE INDEX IDX_1A5F84849586CC8 ON Entidade (cidade_id);
ALTER TABLE Vaga ADD entidade_id INT DEFAULT NULL, ADD created_at DATETIME NOT NULL, DROP entidade;
ALTER TABLE Vaga ADD CONSTRAINT FK_963E82DBA2DAE88B FOREIGN KEY (entidade_id) REFERENCES Entidade (id);
CREATE INDEX IDX_963E82DBA2DAE88B ON Vaga (entidade_id);
ALTER TABLE Voluntario ADD cidade_id INT DEFAULT NULL, ADD created_at DATETIME NOT NULL, DROP cidade, DROP estado;
ALTER TABLE Voluntario ADD CONSTRAINT FK_6E3F322E9586CC8 FOREIGN KEY (cidade_id) REFERENCES Cidade (id);
CREATE INDEX IDX_6E3F322E9586CC8 ON Voluntario (cidade_id);
